name: compile-on-push
on: push

defaults:
  run:
    shell: bash

jobs:
  compile:

    runs-on: ubuntu-latest
    # Credit to DeLaGuardo for this GitHub Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.1.693
      - name: Install rlwrap
        uses: hanslub42/rlwrap@master
      - name: Compile
        run: make
