name: compile-on-push
on: push

defaults:
  run:
    shell: bash

jobs:
  compile:

    runs-on: ubuntu-latest
    # Credit to DeLaGuardo for this GitHub Action
    steps:
    - name: Checkout
      uses: actions/checkout@latest
    - name: Prepare Java
      with:
        java-version: 1.8
    - name: Install clojure tools-deps
      uses: ./
      with:
        cli: 1.10.1.693
    - name: Compile
      run: make
