name: compile-on-push
on: push

defaults:
  run:
    shell: bash

jobs:
  compile:

    runs-on: ubuntu-latest
    # Credit to DeLaGuardo for this GitHub Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.1.693
      - name: Compile
        run: make
      - uses: EndBug/add-and-compile@v5
        with:
          add: 'target/uberjar/matr.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #- name: Add Uberjar
      #  run: git add -f target/uberjar/matr.jar
      #- name: Commit Uberjar
        # Use same commit message as push that triggered github action
      #  run: git commit -m "auto compile new uberjar"
      #- name: Fetch from master
      #  run: git fetch origin master
      #- name: Push code to master
      #  run: git push origin HEAD:master
